server:
  port: 8090
  servlet:
    context-path: /protal
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
spring:
  application:
    name: me-protal
  resources:
    static-locations: classpath:/static/,classpath:/templates/
  mvc:
    view:
      suffix: .html
  datasource:
    url: jdbc:mysql://192.168.0.241:3306/protal?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: zyhk123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      connection-timeout: 30000
      maximum-pool-size: 30
      connection-test-query: SELECT 1
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
  mail:
    host: smtp.qq.com
    username: haoitteam@qq.com
    password: fygpwzcqcpxtbieh
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis:
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.protal.me.dao: debug
    com.zaxxer.hikari: debug